set nocompatible
filetype off
set guifont=Menlo\ for\ Powerline

" Load Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Bundle 'scrooloose/nerdtree'
Bundle 'altercation/vim-colors-solarized'
Bundle 'tpope/vim-fugitive'
Bundle 'kien/ctrlp.vim'
Bundle 'ervandew/supertab'
Bundle 'scrooloose/nerdcommenter'
Bundle 'LaTeX-Box-Team/LaTeX-Box'
Bundle 'tell-k/vim-autopep8'
Bundle 'davidhalter/jedi-vim'
Bundle 'klen/python-mode'

call vundle#end()
filetype plugin indent on

" Color/Syntax highlighting
syntax enable
filetype plugin indent on

set encoding=utf-8

set background=dark
colorscheme solarized

set autoindent
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2

set foldmethod=syntax
set foldlevel=99

set backspace=indent,eol,start "make backspace work like most other apps

" Search
set ignorecase " ignore cases
set smartcase  " unless the string contains uppercase letters
set incsearch  " search while typing

" Display line numbers
set nu

" Airline
let g:airline_theme='powerlineish'
let g:airline_powerline_fonts = 1
set laststatus=2
set t_Co=256

" Tagbar
nmap <leader>. :TagbarToggle<CR>

" Set Shell to bash so fugitive behaves nicely
set shell=/bin/bash

" Move easier between Tabs
map  <C-l> :tabn<CR>
map  <C-h> :tabp<CR>

" Leader maps
let mapleader = ','
let maplocalleader = ','

nmap <leader><Space> :NERDTreeToggle<CR>

nmap <leader>gs :Gstatus<CR>
nmap <leader>gc :Gcommit<CR>
nmap <leader>gd :Gdiff<CR>

let g:LatexBox_viewer='open -a Skim'
let g:LatexBox_quickfix=4

imap <buffer> [[     \begin{
imap <buffer> ]]     <Plug>LatexCloseCurEnv
nmap <leader>li diwi\textit{<ESC>pi<Right>}
nmap <leader>lb diwi\textbf{<ESC>pi<Right>}
