set nocompatible
filetype off
if !has("gui_running")
  set guifont=Menlo\ for\ Powerline
endif

" Load Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Bundle 'scrooloose/nerdtree'
Bundle 'altercation/vim-colors-solarized'
Bundle 'tpope/vim-fugitive'
Bundle 'ctrlpvim/ctrlp.vim'
Bundle 'ervandew/supertab'
Bundle 'scrooloose/nerdcommenter'
Bundle 'LaTeX-Box-Team/LaTeX-Box'
Bundle 'tell-k/vim-autopep8'
Bundle 'davidhalter/jedi-vim'
Bundle 'klen/python-mode'
Bundle 'godlygeek/tabular'
Bundle 'sheerun/vim-polyglot'
Bundle 'davidbeckingsale/writegood.vim'

call vundle#end()
filetype plugin indent on

" Color/Syntax highlighting
syntax enable
filetype plugin indent on

set encoding=utf-8

set background=dark
colorscheme solarized

set autoindent
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2

set foldmethod=syntax
set foldlevel=99

set backspace=indent,eol,start "make backspace work like most other apps

" Search
set ignorecase " ignore cases
set smartcase  " unless the string contains uppercase letters
set incsearch  " search while typing

" Display line numbers
set nu

" Airline
let g:airline_theme='powerlineish'
let g:airline_powerline_fonts = 1
set laststatus=2
set t_Co=256

let g:airline#extensions#tabline#enabled = 1

" Tagbar
nmap <leader>. :TagbarToggle<CR>

" Set Shell to bash so fugitive behaves nicely
set shell=/bin/bash

" Move easier between buffers
map  <C-l> :bn<CR>
map  <C-h> :bp<CR>

" Leader maps
let mapleader = ','
let maplocalleader = ','

nmap <leader><Space> :NERDTreeToggle<CR>

nmap <leader>gs :Gstatus<CR>
nmap <leader>gc :Gcommit<CR>
nmap <leader>gd :Gdiff<CR>

let g:LatexBox_viewer='open -a Skim'
let g:LatexBox_quickfix=4

nmap <leader>li diwi\textit{<ESC>pi<Right>}
nmap <leader>lb diwi\textbf{<ESC>pi<Right>}

" CtrlP
map <C-I> :CtrlPLine<CR>
let g:ctrlp_custom_ignore = '\v[\/](node_modules|target|dist)|(\.(swp|ico|git|svn))$'
let g:ctrlp_max_files = 10000

if exists("g:ctrlp_user_command")
  unlet g:ctrlp_user_command
endif

if executable('ag')
  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup
      \ --ignore .git
      \ --ignore "**/*.swp"
      \ --ignore "*.blg"
      \ --ignore .svn
      \ --ignore .hg
      \ --ignore .DS_Store
      \ --ignore "**/*.pyc"
      \ -g ""'

  " ag is fast enough such that caching could even be turned off
  "let g:ctrlp_use_caching = 0
else
  " Fall back if Ag is not available
  let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$'
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . --cached --exclude-standard --others']
endif
