set nocompatible " Don't emulate vi bugs
filetype off     " required by vundle

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
Bundle 'gmarik/vundle'

Bundle 'tpope/vim-fugitive'
Bundle 'kien/ctrlp.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'Lokaltog/vim-powerline'
Bundle 'altercation/vim-colors-solarized'
Bundle 'majutsushi/tagbar'
Bundle 'Lokaltog/vim-easymotion'

set encoding=utf-8

" Color/Syntax highlighting
syntax enable
filetype plugin indent on
set background=dark
colorscheme solarized


" Leader maps
let mapleader = ','
" NERDTree 
nmap <leader><Space> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif "Close Vim if NERDTree is the only open window

" Tagbar
nmap <leader>l :TagbarToggle<CR>
let g:tagbar_sort = 0 "sort tags according to order in source

" Set Shell to bash so fugitive behaves nicely
set shell=/bin/bash

" Powerline settings
set laststatus=2
set t_Co=256
let g:Powerline_symbols='fancy'

set backspace=2 " make backspace work like most other apps

" Set tab width to 4 spaces
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

set colorcolumn=80 "highlight col 80

" Search
set ignorecase " ignore cases
set smartcase  " unless the string contains uppercase letters
set incsearch  " search while typing

" Display line numbers
set nu

" Move easier between Tabs
map  <C-l> :tabn<CR>
map  <C-h> :tabp<CR>

" Mappings for fugitive
nmap <leader>gs :Gstatus<CR>
nmap <leader>gc :Gcommit<CR>
nmap <leader>gd :Gdiff<CR>

" vim-easymotion
let g:EasyMotion_leader_key = '<Leader>'
